backend:
  name: git-gateway
  branch: master
media_folder: "bowling/static/"
public: "/bowling/static"


collections:
  - name: "News"
    label: "News"
    folder: "bowling/content/post/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "News"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "news.jpg",}
    - {label: "Header Image", name: image, widget: string, default: "news.jpg"}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Weight", name: "weight", widget: "number", default: "9", min: "3"}

  - name: "Tournaments"
    label: "Tournaments"
    folder: "bowling/content/post/tournaments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "Tournaments"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "tournament.jpg"}
    - {label: "Header Image", name: image, widget: string, default: "tournament.jpg"}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Weight", name: "weight", widget: "number", default: "9", min: "3"}

  - name: "honor_scores"
    label: "Honor_Scores"
    folder: "bowling/content/post/honor_scores"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "Scores"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "fireworks.jpg"}
    - {label: "Header Image", name: image, widget: string, default: "fireworks.jpg"}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Weight", name: "weight", widget: "number", default: "9", min: "3"}

  - name: "Bylaws"
    label: "Bylaws"
    folder: "bowling/content/post/bylaws"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "Bylaws"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "flag.jpg"}
    - {label: "Header Image", name: image, widget: string, default: "flag.jpg"}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Weight", name: "weight", widget: "number", default: "9", min: "3"}

  - name: "General"
    label: "General"
    folder: "bowling/content/post/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "news.jpg",}
    - {label: "Header Image", name: image, widget: string, default: "news.jpg"}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Weight", name: "weight", widget: "number", default: "9", min: "3"}