backend:
  name: git-gateway
  branch: master
media_folder: "bowling/static"
public: "/"


collections:
  - name: "news"
    label: "News"
    folder: "bowling/content/post/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "[news]"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: hidden, default: "news.jpg"}
    - {label: Commenting, name: comments, widget: boolean, default: false}
    - {label: Sharing, name: share, widget: boolean, default: false}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}

  - name: "tournaments"
    label: "Tournaments"
    folder: "bowling/content/post/tournaments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "[tournament]"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: hidden, default: "tournament.jpg"}
    - {label: Commenting, name: comments, widget: boolean, default: false}
    - {label: Sharing, name: share, widget: boolean, default: false}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}

  - name: "honor_scores"
    label: "Honor_Scores"
    folder: "bowling/content/post/honor_scores"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "[honor]"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: hidden, default: "fireworks.jpg"}
    - {label: Commenting, name: comments, widget: boolean, default: false}
    - {label: Sharing, name: share, widget: boolean, default: false}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}

  - name: "bylaws"
    label: "Bylaws"
    folder: "bowling/content/post/bylaws"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
    - {label: "Categories", name: "categories", widget: "hidden", default: "[bylaws]"}
    - {label: Author, name: author, widget: hidden, default: SNHUSBC}
    - {label: Author Image, name: authorImage, widget: hidden, default: "bowling/static/snhusbc.jpg"}
    - {label: "Header Image", name: image, widget: image, default: "flag.jpg"}
    - {label: Commenting, name: comments, widget: boolean, default: false}
    - {label: Sharing, name: share, widget: boolean, default: false}
    - {label: Type, name: type, widget: hidden, default: "post"}
    - {label: "Body", name: "body", widget: "markdown"}